version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: flask_backend

    ports:
    - 5431:5432

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8079:8080
