"""empty message

Revision ID: 6f71738bd24e
Revises: a762be4501c2
Create Date: 2022-02-28 22:20:57.168149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f71738bd24e'
down_revision = 'a762be4501c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisement', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('advertisement', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('ix_advertisement_description', table_name='advertisement')
    op.drop_column('advertisement', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_advertisement_description', 'advertisement', ['description'], unique=False)
    op.alter_column('advertisement', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('advertisement', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
