"""empty message

Revision ID: a762be4501c2
Revises: 
Create Date: 2022-02-24 23:17:35.469448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a762be4501c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisement_description'), 'advertisement', ['description'], unique=True)
    op.create_index(op.f('ix_advertisement_title'), 'advertisement', ['title'], unique=True)
    op.create_index(op.f('ix_advertisement_username'), 'advertisement', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertisement_username'), table_name='advertisement')
    op.drop_index(op.f('ix_advertisement_title'), table_name='advertisement')
    op.drop_index(op.f('ix_advertisement_description'), table_name='advertisement')
    op.drop_table('advertisement')
    # ### end Alembic commands ###
