"""empty message

Revision ID: e37fe2a9454a
Revises: 6f71738bd24e
Create Date: 2022-02-28 22:45:35.476798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37fe2a9454a'
down_revision = '6f71738bd24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('date', sa.Text(), nullable=True))
    op.alter_column('advertisement', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('advertisement', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_index('ix_advertisement_title', table_name='advertisement')
    op.create_index(op.f('ix_advertisement_title'), 'advertisement', ['title'], unique=False)
    op.drop_index('ix_advertisement_username', table_name='advertisement')
    op.create_index(op.f('ix_advertisement_username'), 'advertisement', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertisement_username'), table_name='advertisement')
    op.create_index('ix_advertisement_username', 'advertisement', ['username'], unique=False)
    op.drop_index(op.f('ix_advertisement_title'), table_name='advertisement')
    op.create_index('ix_advertisement_title', 'advertisement', ['title'], unique=False)
    op.alter_column('advertisement', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('advertisement', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('advertisement', 'date')
    # ### end Alembic commands ###
